//CORE_REFERENCE_IMPORTS
//CORE_REFERENCE_IMPORT-weatherapi-SSD_SERVICE_ID_sd_G9e39cpi24JKUzBF
import { weatherapi as SSD_SERVICE_ID_sd_G9e39cpi24JKUzBF } from './sd-services/weatherapi';

export const UserRoutes = [
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-weatherapi-SSD_SERVICE_ID_sd_G9e39cpi24JKUzBF
SSD_SERVICE_ID_sd_G9e39cpi24JKUzBF,
];
